{{- if and .Values.postgres.enabled .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "endorser-service.fullname" . }}-postgres
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "endorser-service.labels" . | nindent 4 }}
spec:
  # Allow traffic from the API and migration job to PostgreSQL
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "endorser-service.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: api
        - podSelector:
            matchLabels:
              {{- include "endorser-service.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: migration
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.service.port }}
    {{- with .Values.networkPolicy.postgres.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
{{- end }}
