apiVersion: v2
name: endorser-service
description: A Helm chart for ACA-Py Endorser Service

type: application
version: 0.2.0
appVersion: "1.1.1"
maintainers:
  - email: emiliano.sune@quartech.com
    name: esune
    url: https://github.com/esune
  - email: ivan.polchenko@quartech.com
    name: i5okie
    url: https://github.com/i5okie
dependencies:
  - name: acapy
    version: "0.2.3"
    repository: "https://openwallet-foundation.github.io/helm-charts/"
    condition: acapy.enabled
  - name: postgresql
    version: "16.3.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
