apiVersion: v2
name: vc-authn-oidc
description: A Helm chart to deploy ACAPy VC-AuthN on OpenShift
type: application

appVersion: "2.3.6"
version: 1.1.0

maintainers:
  - email: emiliano.sune@quartech.com
    name: esune
    url: https://github.com/esune
  - email: ivan.polchenko@quartech.com
    name: i5okie
    url: https://github.com/i5okie

# Charts the vc-authn-oidc service depends on
dependencies:
  - name: acapy
    version: 0.2.3
    repository: https://openwallet-foundation.github.io/helm-charts/
  - name: mongodb
    version: 0.10.3
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: mongodb.enabled
  - name: common
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - bitnami-common
    version: 2.x.x
