{{- if and .Values.redis.enabled .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "global.fullname" . }}-redis
  labels:
    {{- include "vc-authn-oidc.redis.labels" . | nindent 4 }}
spec:
  # Allow traffic from the controller to Redis
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "vc-authn-oidc.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
  podSelector:
    matchLabels:
      {{- include "vc-authn-oidc.redis.selectorLabels" . | nindent 6 }}
{{- end }}