{{- if and .Values.proxy.enabled .Values.proxy.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "endorser-service.fullname" . }}-proxy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "endorser-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "endorser-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: proxy
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow all (cluster internal) if no user rules provided
    {{- if .Values.proxy.networkPolicy.extraIngress | len }}
    {{- toYaml .Values.proxy.networkPolicy.extraIngress | nindent 4 }}
    {{- else }}
    - {}
    {{- end }}
  egress:
    {{- if .Values.proxy.networkPolicy.egress | len }}
    {{- toYaml .Values.proxy.networkPolicy.egress | nindent 4 }}
    {{- else }}
    - {}
    {{- end }}
{{- end }}
