{{- if .Values.cleanup.cronjob.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ include "global.fullname" . }}-cronjob
  labels:
    {{- include "vc-authn-oidc.labels" . | nindent 4 }}
spec:
  # Allow traffic from the agent to the controller
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{ include "vc-authn-oidc.selectorLabels" . | nindent 14 }}
              component: cleanup
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  podSelector:
    matchLabels:
      {{- include "vc-authn-oidc.selectorLabels" . | nindent 6 }}
{{- end -}}
